# Built with Jekyll 3.2.0

# Setup
title:               Ajinkya Jain
tagline:             'University of Texas at Austin'
description:         'Ajinkya Jain'
url:                 'https://jainajinkya.github.io'
baseurl:             ''

# About/contact
# author:
#   name:              Alex Gil
#   url:               https://twitter.com/elotroalex
#   email:             colibri.alex@gmail.com
author:
  name:              Ajinkya Jain
  url:               https://jainajinkya.github.io
  email:             ajinkya@utexas.edu

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."


